platform :ios, '6.0'
pod 'AFNetworking', '1.3.3', '< 2.0'
pod 'EasyMapping', '~>0.5.3'
pod 'WYPopoverController', '~> 0.1.7'
pod 'NSString-HTML', :podspec =>'https://raw.githubusercontent.com/bespalown/NSString-HTML/master/NSString-HTML.podspec'
pod 'HMSegmentedControl', '~> 1.3.0'
pod 'SHSPhoneComponent', '< 2.0'
pod 'ISO8601DateFormatter'
pod 'SVPulsingAnnotationView'
pod 'NUI'
pod 'TTTAttributedLabel'
pod 'MBProgressHUD'
pod 'Reachability'
pod 'RESideMenu'
#localPods
#pod 'IQActionSheetPickerView'